{{--
    Brand favicons.

    Icons live in public/images/icons and are generated by build-favicon.php.
    The light set is declared first as the default; the dark set repeats the
    same sizes behind `prefers-color-scheme: dark` so the tab, bookmarks and
    pinned shortcuts follow the OS colour scheme.
--}}
<link rel="icon" href="{{ asset('favicon.ico') }}" sizes="32x32">

<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('images/icons/icon-light-16x16.png') }}">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('images/icons/icon-light-32x32.png') }}">
<link rel="icon" type="image/png" sizes="64x64" href="{{ asset('images/icons/icon-light-64x64.png') }}">
<link rel="icon" type="image/png" sizes="128x128" href="{{ asset('images/icons/icon-light-128x128.png') }}">

<link rel="icon" type="image/png" sizes="16x16" href="{{ asset('images/icons/icon-dark-16x16.png') }}" media="(prefers-color-scheme: dark)">
<link rel="icon" type="image/png" sizes="32x32" href="{{ asset('images/icons/icon-dark-32x32.png') }}" media="(prefers-color-scheme: dark)">
<link rel="icon" type="image/png" sizes="64x64" href="{{ asset('images/icons/icon-dark-64x64.png') }}" media="(prefers-color-scheme: dark)">
<link rel="icon" type="image/png" sizes="128x128" href="{{ asset('images/icons/icon-dark-128x128.png') }}" media="(prefers-color-scheme: dark)">

<link rel="apple-touch-icon" sizes="180x180" href="{{ asset('apple-touch-icon.png') }}">
<link rel="manifest" href="{{ asset('manifest.json') }}">
